[package]
name = "ferris-vault-tui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tui"
path = "tui/src/main.rs"

[workspace]
members = [
    "tui",
    "app-core", 
    "cryptography", 
    "password-generator", 
    "vault-manager",
]
