[package]
name = "cryptography"
version = "0.1.0"
edition = "2024"

[dependencies]
app-core = { path = "../app-core" }
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
hkdf = "0.12.4"
sha2 = "0.10.9"
